name: OpenNotebook Download

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Pull and Save Image
      run: |
        # 强制拉取兼容性最高的 1.5.4 稳定版数据库
        docker pull surrealdb/surrealdb:v1.5.4
        docker save surrealdb/surrealdb:v1.5.4 -o surrealdb-v1.tar
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: surrealdb-v1-image
        path: surrealdb-v1.tar




