name: OpenNotebook Download

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Pull and Save Image
      run: |
        docker pull ghcr.io/open-notebook/open-notebook:latest
        docker save ghcr.io/open-notebook/open-notebook:latest -o open-notebook.tar
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: open-notebook-image
        path: open-notebook.tar
